FROM telegraf:latest

# Copiamos la configuración personalizada al contenedor
COPY telegraf.conf /etc/telegraf/telegraf.conf

CMD ["telegraf", "--config", "/ESP32 - P2 - E02/telegraf/telegraf.conf"]
