[agent]
  interval = "10s"
  round_interval = true
  metric_batch_size = 1000
  metric_buffer_limit = 10000
  collection_jitter = "0s"
  flush_interval = "10s"
  flush_jitter = "0s"
  precision = ""
  debug = false
  quiet = false
  logfile = ""
  hostname = ""
  omit_hostname = false

# --- ENTRADA: HiveMQ Cloud ---
[[inputs.mqtt_consumer]]
  servers = ["tls://a3022985d40540ce9d4b29fe5a528c35.s1.eu.hivemq.cloud:8883"]
  topics = ["sensores/#"]
  username = "pablolz"
  password = "pablolz123"
  data_format = "json"

# --- SALIDA: InfluxDB Cloud ---
[[outputs.influxdb_v2]]
  urls = ["https://us-east-1-1.aws.cloud2.influxdata.com"]
  token = "zrk2TeDoAt-3n-moK8zwou4y0F0lrHF5lexzRUeNP6LV-6A0eWCd1v674QW6E9RZs0qkl5qFl6grNfJ2fI5b8w=="
  organization = "Grupo iot"
  bucket = "flujo de datos / sensores"